---
- name: minecraft
  hosts: '{{ target }}'
  become: True
  become_user: root
  tasks:

    - name: java
      yum:
        name: "{{ repo_packages }}"
        state: latest
      vars:
        repo_packages:
          - java-1.8.0-openjdk-headless

    - name: minecraft user
      user:
        name: minecraft
        shell: /sbin/nologin

    - name: minecraft dirs
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: minecraft
        group: minecraft
      with_items:
        - /opt/minecraft
        - /opt/minecraft/backups
        - /opt/minecraft/server
        - /opt/minecraft/tmp

    - name: get jar download page
      get_url:
        url: https://www.minecraft.net/en-us/download/server
        dest: /opt/minecraft/tmp/mc_jar_url.html
        mode: '0444'
        owner: minecraft
        group: minecraft

    - name: determine jar url
      shell: awk -F '"' '/\.jar/ {print $2; exit}' /opt/minecraft/tmp/mc_jar_url.html
      register: mc_jar_url

    - name: get jar
      get_url:
        url: "{{ mc_jar_url.stdout }}"
        dest: /opt/minecraft/server/server.jar
        mode: '0444'
        owner: minecraft
        group: minecraft

    - name: determine if eula exists
      stat:
        path: /opt/minecraft/server/eula.txt
      register: mc_eula_file

    - name: run jar when eula not exists (max 60 seconds)
      shell:
        chdir: /opt/minecraft/server/
        cmd: timeout 60 java -Xmx1024M -Xms512M -jar server.jar nogui
      ignore_errors: yes
      when: mc_eula_file.stat.exists == False

    - name: agree to eula
      lineinfile:
        path: /opt/minecraft/server/eula.txt
        line: 'eula=true'
        mode: '0444'
        owner: minecraft
        group: minecraft

    - name: minecraft systemd unit file
      copy:
        src: minecraft.service
        dest: /etc/systemd/system/minecraft.service
        mode: '0444'
        owner: root
        group: root

    - name: set server.properties file
      copy:
        src: server.properties
        dest: /opt/minecraft/server/server.properties
        mode: '0600'
        owner: minecraft
        group: minecraft

    - name: start/enable minecraft service
      systemd:
        state: started
        enabled: yes
        daemon_reload: yes
        name: minecraft
